### ISSUE TITLE
server-side rendering

### ISSUE THREAD

**Issue by bkinsey808** [apollostack/apollo-server#16]
Is integrating with angular universal on the radar for this project?

https://universal.angular.io/quickstart/

**Comment by helfer** [comment]
I'm not familiar with angular universal. What is it, and what would it mean to integrate with it?

**Comment by bkinsey808** [comment]
It speeds up angular 2 apps significantly, especially on the initial page, by rendering on the server. The react ecosystem also has server side rendering, but I've never played with it. A good full stack system really ought to have it. As far as i know, angular universal has so far only been implemented for express, and not hapi, koa, etc.

**Comment by helfer** [comment]
Ah I see. This is mostly up to the view layer integration, I think. The GraphQL server will have very little to do with this and should just work out of the box for it.

I think we have somethin in the pipelines for the react-bindings: https://github.com/apollostack/react-apollo/issues/54

For something similar in Angular, you should probably close the issue here and open it on the angular2-apollo repo: https://github.com/apollostack/angular2-apollo

**Comment by bkinsey808** [comment]
But server side rendering must be done on the server. So it is not really a client side issue. However it is true that the angular universal server could be run on a separate server than the api (graphql) server. It seems like apollo project as a whole needs to think about this assuming it is serious about deeply integrating with angular 2.

**Comment by helfer** [comment]
Yes, it has to be done on a server, but it doesn't affect the graphql part of the server. The more challenging part is making sure that whatever code people write for the frontend can be rendered by the server as well, which is why I think it makes most sense if @Urigo takes a look first. If there's anything we need to do server-side to make it possible, I can take care of that.

**Comment by bkinsey808** [comment]
sounds good, thanks.
